# Generated by Django 4.2.6 on 2023-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name0', models.CharField(max_length=100)),
                ('cUnit_price0', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name1', models.CharField(max_length=100)),
                ('cUnit_price1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name2', models.CharField(max_length=100)),
                ('cUnit_price2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name3', models.CharField(max_length=100)),
                ('cUnit_price3', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name4', models.CharField(max_length=100)),
                ('cUnit_price4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name5', models.CharField(max_length=100)),
                ('cUnit_price5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name6', models.CharField(max_length=100)),
                ('cUnit_price6', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name7', models.CharField(max_length=100)),
                ('cUnit_price7', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name8', models.CharField(max_length=100)),
                ('cUnit_price8', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='menu9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cProduct_name9', models.CharField(max_length=100)),
                ('cUnit_price9', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='yellow_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cStore_Name', models.CharField(max_length=30)),
                ('cStore_Phone', models.CharField(max_length=50)),
                ('cStore_Addr', models.CharField(blank=True, default='', max_length=255)),
                ('cBusiness_Hours', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
