# Generated by Django 4.2.6 on 2023-11-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_cproduct_name0_menu_all_cproduct_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu0',
        ),
        migrations.DeleteModel(
            name='menu1',
        ),
        migrations.DeleteModel(
            name='menu2',
        ),
        migrations.DeleteModel(
            name='menu3',
        ),
        migrations.DeleteModel(
            name='menu4',
        ),
        migrations.DeleteModel(
            name='menu5',
        ),
        migrations.DeleteModel(
            name='menu6',
        ),
        migrations.DeleteModel(
            name='menu7',
        ),
        migrations.DeleteModel(
            name='menu8',
        ),
        migrations.DeleteModel(
            name='menu9',
        ),
    ]
